Repository EmilGedda/Darkside, pull requests merged in 2019-03, with the labels that each got.

#1 set up jest and add test example
  jest.config.js
  package-lock.json
  package.json
  src/sum.ts
  test/dummy.ts
  test/sum.ts
Labels: enhancement

#2 add Vector2 class
  src/vector2.ts
  test/vector2.ts
Labels: enhancement

#3 add Material class
  src/material.ts
  test/material.ts
Labels: enhancement

#4 add Wavelength, RGB, and XYZ classes
  src/rgb.ts
  src/wavelength.ts
  src/xyz.ts
  test/rgb.ts
  test/wavelength.ts
  test/xyz.ts
Labels: enhancement

#5 basic rendering and 2D figures done
  .eslintrc.json
  .prettierrc
  css/canvas.css
  package-lock.json
  package.json
  src/app.ts
  src/draw.ts
  src/grid.ts
  src/index.html
  src/lightsource.ts
  src/material.ts
  src/polygon.ts
  src/prism.ts
  src/renderconfig.ts
  src/sum.ts
  src/vector2.ts
  src/wavelength.ts
  test/material.ts
  test/sum.ts
  test/vector2.ts
  tsconfig.json
  webpack.config.js
Labels: enhancement

#7 add a renderloop and lock it to 60fps
  src/app.ts
  src/grid.ts
Labels: enhancement

#9 fix diff output bug
  .circleci/config.yml
Labels: bug

#8 render lightsource beams and blend their colors
  .eslintrc.json
  src/app.ts
  src/draw.ts
  src/grid.ts
  src/lightsource.ts
  src/prism.ts
  src/renderconfig.ts
  src/rgb.ts
  src/vector2.ts
Labels: enhancement

#11 use JSON file to create Material
  src/data/materials.json
  src/material.ts
  src/prism.ts
  test/material.ts
  tsconfig.json
Labels: enhancement

#12 Feature/minification
  package-lock.json
  package.json
  src/app.ts
  src/index.html
  webpack.config.js
Labels: enhancement

#13 only copy index.html when deploying
  .circleci/config.yml
  src/app.ts
Labels: performance

#14 Snell's law
  src/data/materials.json
  src/material.ts
  src/wavelength.ts
  test/material.ts
  test/wavelength.ts
Labels: enhancement

#10 render lightsource beams as sine curves
  package-lock.json
  package.json
  src/app.ts
  src/draw.ts
  src/grid.ts
  src/lightsource.ts
  src/polygon.ts
  src/prism.ts
  src/renderconfig.ts
  src/vector2.ts
  test/vector2.ts
Labels: enhancement

#15 add Schott SF10 glass
  src/data/materials.json
  src/material.ts
  test/material.ts
Labels: enhancement
